config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   confirmations: 'users/confirmations',
                   registrations: 'users/registrations'
                 }
  root 'static_public#landing_page'
  get 'privacy', to: 'static_public#privacy'
  get 'terms', to: 'static_public#terms'
  get 'pricing', to: 'static_public#pricing'
  get 'about', to: 'static_public#about'

  resources :comments, only: [] do
    resources :comments, only: %i[new create destroy], module: :comments
  end

  resources :posts do
    resources :comments, only: %i[new create destroy], module: :posts
    member do
      patch "upvote", to: "posts#upvote"
      patch "downvote", to: "posts#downvote"
      patch "bookmark", to: "posts#bookmark"
      patch "complete", to: "posts#complete"
      patch "watchlist", to: "posts#watchlist"
    end
  end

  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]

  resources :users, only: %i[index show]

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true, counter_cache: true, inverse_of: :comments
  has_many :comments, as: :commentable, dependent: :destroy

  MIN_BODY_LENGTH = 2
  MAX_BODY_LENGTH = 1000

  validates :body, presence: true
  validates :body, length: { minimum: MIN_BODY_LENGTH, maximum: MAX_BODY_LENGTH }

  def destroy
    update(deleted_at: Time.zone.now)
  end

  def find_parent
    return commentable unless commentable.is_a?(Comment)

    commentable.find_parent
  end
end

app/controllers/comments/comments_controller.rb
# frozen_string_literal: true

module Comments
  class CommentsController < CommentsController
    private

    def set_commentable
      @commentable = Comment.find(params[:comment_id])
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_commentable

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.build(comment_params)
    if @comment.save
      redirect_to @commentable unless @commentable.is_a?(Comment)
      redirect_to @commentable.find_parent if @commentable.is_a?(Comment)
      flash[:notice] = 'Comment created'
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to @commentable unless @commentable.is_a?(Comment)
      redirect_to @commentable.find_parent if @commentable.is_a?(Comment)
      flash[:alert] = 'Comment deleted'
    else
      redirect_to @commentable, alert: 'Something went wrong'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < CommentsController
    private

    def set_commentable
      @commentable = Post.find(params[:post_id])
    end
  end
end

app/views/comments/_comment.html.erb
<div class='comment'>
  <% if comment.deleted_at.present? %>
    <i>
      Comment has been deleted
    </i>
  <% else %>
    <%= comment.created_at %>
    by
    <%= link_to comment.user.name, comment.user %>
    <%= markdown(comment.body) %>
    <%= link_to 'Delete', [@commentable, comment], method: :delete %>
  <% end %>
  comments:
  <%= comment.comments_count %>
  <%= link_to 'Reply', new_comment_comment_path(comment) %>
  <br>
  <%= render comment.comments %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@commentable, comment]) do |form| %>
  <%= render 'layouts/errors', form: form %>

  <div class="field" data-controller="character-counter">
    <%= form.text_area :body,
      style: "width: 100%",
      rows: 2,
      data: { controller: "textarea-autogrow", character_counter_target: 'input' },
      maxlength: Comment::MAX_BODY_LENGTH, 
      placeholder: 'Add a comment here. User Markdown for formatting' 
    %>
    <strong data-character-counter-target="counter"></strong>/<%= Comment::MAX_BODY_LENGTH%> characters
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var form = document.querySelector("#<%= dom_id(@commentable, 'form') %>")
if (form != null) {
  form.classList.toggle("display-none")
}

var comments = document.querySelector("#<%= dom_id(@commentable) %>")
if (comments == null) {
  comments = document.querySelector("#comments")
}
comments.insertAdjacentHTML('beforeend', '<%= j render 'comments/comment', commentable: @commentable, comment: @comment %>')

app/views/comments/new.html.erb
New comment for

<%= link_to @commentable.title, @commentable unless @commentable.is_a?(Comment) %>
<%= link_to @commentable.find_parent.title, @commentable.find_parent if @commentable.is_a?(Comment) %>
<%= render 'comments/form', comment: @comment %>

app/views/comments/new.js.erb
var form = document.querySelector('#<%= dom_id(@commentable, 'form') %>')
form.classList.toggle('display-none')