config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   confirmations: 'users/confirmations',
                   registrations: 'users/registrations'
                 }
  root 'static_public#landing_page'
  get 'privacy', to: 'static_public#privacy'
  get 'terms', to: 'static_public#terms'
  get 'pricing', to: 'static_public#pricing'
  get 'about', to: 'static_public#about'

  resources :comments, only: [] do
    resources :comments, only: %i[new create destroy], module: :comments
  end

  resources :posts do
    resources :comments, only: %i[new create destroy], module: :posts
    member do
      patch "upvote", to: "posts#upvote"
      patch "downvote", to: "posts#downvote"
      patch "bookmark", to: "posts#bookmark"
      patch "complete", to: "posts#complete"
      patch "watchlist", to: "posts#watchlist"
    end
  end

  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]

  resources :users, only: %i[index show]

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_many :comments, -> { order(created_at: :desc) }, as: :commentable, dependent: :destroy, inverse_of: :commentable
  has_many :taggings, dependent: :destroy
  has_many :tags, -> { order(:name) }, through: :taggings

  acts_as_votable

  extend FriendlyId
  friendly_id :title, use: %i[slugged finders history]

  def should_generate_new_friendly_id?
    title_changed?
  end

  validates :title, presence: true
  validates :description, presence: true
  validates :body, presence: true

  MAX_TITLE_LENGTH = 140
  MAX_DESCRIPTION_LENGTH = 200
  MAX_BODY_LENGTH = 50_000

  validates :title, length: { maximum: MAX_TITLE_LENGTH }
  validates :description, length: { maximum: MAX_DESCRIPTION_LENGTH }
  validates :body, length: { maximum: MAX_BODY_LENGTH }

  scope :free, -> { where(premium: false) }
  scope :premium, -> { where(premium: true) }

  def upvote!(user)
    if user.voted_up_on? self, vote_scope: 'like'
      unvote_by user, vote_scope: 'like'
    else
      upvote_by user, vote_scope: 'like'
    end
  end

  def downvote!(user)
    if user.voted_down_on? self, vote_scope: 'like'
      unvote_by user, vote_scope: 'like'
    else
      downvote_by user, vote_scope: 'like'
    end
  end

  def bookmark!(user)
    if user.voted_up_on? self, vote_scope: 'bookmark'
      unvote_by user, vote_scope: 'bookmark'
    else
      upvote_by user, vote_scope: 'bookmark'
    end
  end

  def complete!(user)
    if user.voted_up_on? self, vote_scope: 'watchlist'
      unvote_by user, vote_scope: 'watchlist'
    else
      upvote_by user, vote_scope: 'watchlist'
    end
  end

  def watchlist!(user)
    if user.voted_down_on? self, vote_scope: 'watchlist'
      unvote_by user, vote_scope: 'watchlist'
    else
      downvote_by user, vote_scope: 'watchlist'
    end
  end

  def upvote_percentage
    cached_scoped_like_votes_up.to_d / cached_scoped_like_votes_total.to_d * 100
  end

  def downvote_percentage
    cached_scoped_like_votes_down.to_d / cached_scoped_like_votes_total.to_d * 100
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < CommentsController
    private

    def set_commentable
      @commentable = Post.find(params[:post_id])
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_post, only: %i[show edit update destroy upvote downvote bookmark watchlist complete]

  def index
    @q = Post.order(created_at: :desc).ransack(params[:q])
    @pagy, @posts = pagy(@q.result.includes(:user, :taggings, taggings: :tag))
    @tags = Tag.pluck(:name, :id)
  end

  def upvote
    @post.upvote! current_user
    render 'vote.js.erb'
  end

  def downvote
    @post.downvote! current_user
    render 'vote.js.erb'
  end

  def bookmark
    # upvote
    @post.bookmark! current_user
    render 'vote.js.erb'
  end

  def complete
    # upvote
    @post.complete! current_user
    render 'vote.js.erb'
  end

  def watchlist
    # downvote
    @post.watchlist! current_user
    render 'vote.js.erb'
  end

  def show
    set_meta_tags title: @post.title,
                  description: @post.description,
                  keywords: 'Site, Login, Members'

    if @post.premium? && current_user&.subscription_status != 'active'
      redirect_to posts_path, alert: 'You are not a premium subscriber'
    end

    @commentable = @post
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    set_meta_tags title: "#{action_name.capitalize} #{controller_name.singularize.capitalize}"
    @post = Post.new
  end

  def edit
    set_meta_tags title: "#{action_name.capitalize} #{controller_name.singularize.capitalize}"
    redirect_to posts_path, alert: 'You are not authorized' unless @post.user == current_user
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.user == current_user
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to posts_path, alert: 'You are not authorized'
    end
  end

  def destroy
    if @post.user == current_user
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    else
      redirect_to posts_path, alert: 'You are not authorized'
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])

    # post_path is only for SHOW action
    # if request.path != post_path(@post)
    #   return redirect_to @post, :status => :moved_permanently
    # end
  end

  def post_params
    params.require(:post).permit(:title, :body, :premium, :description, tag_ids: [])
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def premium_label(value)
    case value
    when true
      text = 'Premium'
      badge_color = 'badge bg-danger'
    end
    content_tag(:span, text, class: badge_color)
  end
end

app/views/posts/_bookmark_link.html.erb
<%= content_tag :div, id: "bookmark-#{post.id}" do %>
  <div class='me-4'>
  <%= link_to bookmark_post_path(post), method: :patch, remote: true do %>
    <% if current_user&.voted_up_on? post, vote_scope: 'bookmark' %>
      <i class="fa fa-star text-warning"></i>
    <% else %>
      <i class="far fa-star text-secondary"></i>
    <% end %>
  <% end %>
  </div>
<% end %>

app/views/posts/_complete_link.html.erb
<%= content_tag :div, id: "complete-#{post.id}" do %>
  <div class='ms-4 me-2'>
    <%= link_to complete_post_path(post), method: :patch, remote: true do %>
      <% if current_user&.voted_up_on? post, vote_scope: 'watchlist' %>
        <i class="fa fa-check-square text-success"></i>
      <% else %>
        <i class="far fa-check-square text-secondary"></i>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/posts/_downvote_link.html.erb
<%= content_tag :div, id: "downvote-#{post.id}" do %>
  <%= link_to downvote_post_path(post), method: :patch, remote: true do %>
    <% if current_user&.voted_down_on? post, vote_scope: 'like' %>
      <i class="fa fa-thumbs-down text-danger"></i>
    <% else %>
      <i class="far fa-thumbs-down text-secondary"></i>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <%= render 'layouts/errors', form: form %>

  <div class="field" data-controller="tom-select">
    <%= form.label :tags %>
    <%= form.select :tag_ids, Tag.all.pluck(:name, :id), {}, { multiple: true, id: 'select-tags' } %>
  </div>

  <div class="field" data-controller="character-counter">
    <%= form.label :title %>
    <%= form.text_field :title,
      autocomplete: 'off',
      style: "width: 100%",
      data: { character_counter_target: 'input' },
      maxlength: Post::MAX_TITLE_LENGTH %>
    <strong data-character-counter-target="counter"></strong>/<%= Post::MAX_TITLE_LENGTH%> characters
  </div>

  <div class="field" data-controller="character-counter">
    <%= form.label :description %>
    <%= form.text_field :description,
      autocomplete: 'off',
      style: "width: 100%",
      data: { character_counter_target: 'input' },
      maxlength: Post::MAX_DESCRIPTION_LENGTH %>
    <strong data-character-counter-target="counter"></strong>/<%= Post::MAX_DESCRIPTION_LENGTH%> characters
  </div>

  <div class="field" data-controller="character-counter">
    <%= form.label :body %>
    <%= form.text_area :body,
      style: "width: 100%",
      rows: 8,
      data: { controller: "textarea-autogrow", character_counter_target: 'input' },
      maxlength: Post::MAX_BODY_LENGTH, 
      placeholder: 'User Markdown for formatting' 
    %>
    <strong data-character-counter-target="counter"></strong>/<%= Post::MAX_BODY_LENGTH%> characters
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.check_box :premium %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_like_count.html.erb
<%= content_tag :div, id: "like-count-#{post.id}" do %>
  <div class='ms-2 me-2'>
    <%= post.cached_scoped_like_votes_score %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class='card'>
  <div class='card-header'>
    <h3>
      <%= premium_label(post.premium) %>
      <%= link_to_unless_current highlight(post.title, params.dig(:q, :title_or_description_cont)), post %>
    </h3>
    <p class="fst-italic">
      <%= highlight(post.description, params.dig(:q, :title_or_description_cont)) %>
    </p>
  </div>
  <% if controller_name == 'posts' && action_name == 'show' %>
    <%= render 'layouts/vimeo', vimeo_id: @post.description %>
    <div class='card-body'>
      <%= markdown(post.body) %>
    </div>
  <% end %>
  <% if post.tags.any? %>
    <div class='card-footer'>
      <% post.tags.pluck(:name).each do |tag| %>
        <div class='badge bg-info'>
          <%= tag %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class='card-footer'>
    <h3>
      <div class='d-flex justify-content-center'>
        <%= render 'posts/bookmark_link', post: post %>
        <%= render 'posts/upvote_link', post: post %>
        <%= render 'posts/like_count', post: post %>
        <%= render 'posts/downvote_link', post: post %>
        <%= render 'posts/complete_link', post: post %>
        <%= render 'posts/watchlist_link', post: post %>
      </div>
      <br>
      <%= render 'posts/progress', post: post %>
    </h3>
  </div>
  <div class='card-footer'>
    <div class='float-start'>
      <i class="far fa-comment"></i>
      <%= post.comments_count %>
    </div>
    <div class='float-end'>
      On <%= post.created_at.strftime('%d %b %Y') %>
      by 
      <%= render AvatarComponent.new(src: post.user.image, alt: post.user.name, display: post.user.image?) %>
      <%= link_to post.user.username, post.user %>
    </div>
  </div>
  <% if current_user == post.user %>
    <div class='card-footer'>
      <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-sm btn-warning' %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
    </div>
  <% end %>
</div>
<br>

app/views/posts/_progress.html.erb
<%= content_tag :div, id: "progress-#{post.id}" do %>
  <div class="progress">
    <div class="progress-bar bg-success" role="progressbar" style="width: <%= number_to_percentage(post.upvote_percentage, precision: 0) %>">
      <%= post.cached_scoped_like_votes_up if post.cached_scoped_like_votes_total.nonzero? %>
    </div>
    <div class="progress-bar bg-danger" role="progressbar" style="width: <%= number_to_percentage(post.downvote_percentage, precision: 0) %>">
      <%= post.cached_scoped_like_votes_down if post.cached_scoped_like_votes_total.nonzero? %>
    </div>
  </div>
<% end %>

app/views/posts/_upvote_link.html.erb
<%= content_tag :div, id: "upvote-#{post.id}" do %>
  <%= link_to upvote_post_path(post), method: :patch, remote: true do %>
    <% if current_user&.voted_up_on? post, vote_scope: 'like' %>
      <i class="fa fa-thumbs-up text-success"></i>
    <% else %>
      <i class="far fa-thumbs-up text-secondary"></i>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_watchlist_link.html.erb
<%= content_tag :div, id: "watchlist-#{post.id}" do %>
  <%= link_to watchlist_post_path(post), method: :patch, remote: true do %>
    <% if current_user&.voted_down_on? post, vote_scope: 'watchlist' %>
      <i class="fa fa-clock text-danger"></i>
    <% else %>
      <i class="far fa-clock text-secondary"></i>
    <% end %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<div class='card'>
  <div class='card-header'>
    <h1>Editing Post</h1>
  </div>
  <div class='card-body'>
    <%= render 'form', post: @post %>
  </div>
  <div class='card-footer'>
    <%= link_to 'Cancel', @post, class: 'btn btn-sm btn-secondary' %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>
  Posts:
  <%= @posts.length %>/
  <%= Post.count %>
</h1>

<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>

<%= sort_link(@q, :created_at, default_order: :desc) do %>
  <strong class='text-secondary'>Latest</strong>
<% end %>
<%= sort_link(@q, :cached_votes_score, default_order: :desc) do %>
  <strong class='text-secondary'>Top Rated</strong>
<% end %>

<%= search_form_for @q do |f| %>
  <%= f.label :title_or_description %>
  <%= f.search_field :title_or_description_cont %>

  <%= f.select :premium_eq, [['Premium', true], ['Free', false]], include_blank: 'Type' %>

  <%= f.collection_select :user_name_cont, User.joins(:posts).distinct, :name, :name, include_blank: 'Author' %>

  <%= f.select :taggings_tag_id_eq, @tags, { include_blank: true } %>

  <%= f.submit %>
<% end %>

<% if params[:q].present? %>
  <%= link_to posts_path do %>
    <i class="fa fa-redo"></i>
    Clear Search
  <% end %>
<% end %>

<hr>

<%= render @posts %>

app/views/posts/new.html.erb
<div class='card'>
  <div class='card-header'>
    <h1>New Post</h1>
  </div>
  <div class='card-body'>
    <%= render 'form', post: @post %>
  </div>
  <div class='card-footer'>
    <%= link_to 'Cancel', posts_path, class: 'btn btn-sm btn-secondary' %>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'posts/post', post: @post %>

<div class="container text-center">
  <div class="row">
    <div class="col-md-6">
      Upvoters:
      <br>
      <%= @post.get_upvotes(vote_scope: 'like').by_type(User).voters.pluck(:email) %>
    </div>
    <div class="col-md-6">
      Downvoters:
      <br>
      <%= @post.get_downvotes(vote_scope: 'like').by_type(User).voters.pluck(:email) %>
    </div>
  </div>
</div>

<hr>
<%= render template: 'comments/new' %>
<%= render @comments %>

app/views/posts/vote.js.erb
document.getElementById("like-count-<%= @post.id %>").innerHTML = "<%= j render "posts/like_count", post: @post %>";
document.getElementById("downvote-<%= @post.id %>").innerHTML = "<%= j render "posts/downvote_link", post: @post %>";
document.getElementById("upvote-<%= @post.id %>").innerHTML = "<%= j render "posts/upvote_link", post: @post %>";
document.getElementById("bookmark-<%= @post.id %>").innerHTML = "<%= j render "posts/bookmark_link", post: @post %>";
document.getElementById("complete-<%= @post.id %>").innerHTML = "<%= j render "posts/complete_link", post: @post %>";
document.getElementById("watchlist-<%= @post.id %>").innerHTML = "<%= j render "posts/watchlist_link", post: @post %>";
document.getElementById("progress-<%= @post.id %>").innerHTML = "<%= j render(Posts::ProgressComponent.new(post: @post)) %>";