config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   confirmations: 'users/confirmations',
                   registrations: 'users/registrations'
                 }
  root 'static_public#landing_page'
  get 'privacy', to: 'static_public#privacy'
  get 'terms', to: 'static_public#terms'
  get 'pricing', to: 'static_public#pricing'
  get 'about', to: 'static_public#about'

  resources :comments, only: [] do
    resources :comments, only: %i[new create destroy], module: :comments
  end

  resources :posts do
    resources :comments, only: %i[new create destroy], module: :posts
    member do
      patch "upvote", to: "posts#upvote"
      patch "downvote", to: "posts#downvote"
      patch "bookmark", to: "posts#bookmark"
      patch "complete", to: "posts#complete"
      patch "watchlist", to: "posts#watchlist"
    end
  end

  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]

  resources :users, only: %i[index show]

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end
end

app/views/layouts/_errors.html.erb
<% if form.object.errors.any? %>
  <div class='text-danger'>
    <ul>
      <% form.object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="flex justify-center px-2 py-12 border-t-2 footer" style="background-color:#efebe961;">
  <div class="sticky bottom-0 px-4 pt-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
    <div class="grid gap-10 row-gap-6 mb-8 sm:grid-cols-2 lg:grid-cols-4">
      <div class="sm:col-span-2">
        <a href="/" aria-label="Go home" title="Company" class="inline-flex items-center">
          <%= image_tag "favicon.ico", height: "20", alt: "logo", class: "inline-block align-top w-10" %>
          <span class="ml-2 text-xl font-bold tracking-wide text-gray-800 uppercase">superails</span>
        </a>
        <div class="mt-6 lg:max-w-sm">
          <p class="text-sm text-gray-800">
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.
          </p>
          <p class="mt-4 text-sm text-gray-800">
            Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
          </p>
        </div>
      </div>
      <div class="space-y-2 text-sm">
        <p class="text-base font-bold tracking-wide text-gray-900">Contacts</p>
        <div class="flex">
          <p class="mr-1 text-gray-800">Phone:</p>
          <a href="tel:850-123-5021" aria-label="Our phone" title="Our phone" class="transition-colors duration-300 text-pink-accent-400 hover:text-pink-800">850-123-5021</a>
        </div>
        <div class="flex">
          <p class="mr-1 text-gray-800">Email:</p>
          <a href="mailto:info@lorem.mail" aria-label="Our email" title="Our email" class="transition-colors duration-300 text-pink-accent-400 hover:text-pink-800">info@lorem.mail</a>
        </div>
        <div class="flex">
          <p class="mr-1 text-gray-800">Address:</p>
          <a href="https://www.google.com/maps" target="_blank" rel="noopener noreferrer" aria-label="Our address" title="Our address" class="transition-colors duration-300 text-pink-accent-400 hover:text-pink-800">
            312 Lovely Street, Poland
          </a>
        </div>
      </div>
      <div>
        <span class="text-base font-bold tracking-wide text-gray-900">Social</span>
        <div class="flex items-center mt-1 space-x-3">
          <a href="/" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
            <svg viewBox="0 0 24 24" fill="currentColor" class="h-5">
              <path
                d="M24,4.6c-0.9,0.4-1.8,0.7-2.8,0.8c1-0.6,1.8-1.6,2.2-2.7c-1,0.6-2,1-3.1,1.2c-0.9-1-2.2-1.6-3.6-1.6 c-2.7,0-4.9,2.2-4.9,4.9c0,0.4,0,0.8,0.1,1.1C7.7,8.1,4.1,6.1,1.7,3.1C1.2,3.9,1,4.7,1,5.6c0,1.7,0.9,3.2,2.2,4.1 C2.4,9.7,1.6,9.5,1,9.1c0,0,0,0,0,0.1c0,2.4,1.7,4.4,3.9,4.8c-0.4,0.1-0.8,0.2-1.3,0.2c-0.3,0-0.6,0-0.9-0.1c0.6,2,2.4,3.4,4.6,3.4 c-1.7,1.3-3.8,2.1-6.1,2.1c-0.4,0-0.8,0-1.2-0.1c2.2,1.4,4.8,2.2,7.5,2.2c9.1,0,14-7.5,14-14c0-0.2,0-0.4,0-0.6 C22.5,6.4,23.3,5.5,24,4.6z"
              ></path>
            </svg>
          </a>
          <a href="/" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
            <svg viewBox="0 0 30 30" fill="currentColor" class="h-6">
              <circle cx="15" cy="15" r="4"></circle>
              <path
                d="M19.999,3h-10C6.14,3,3,6.141,3,10.001v10C3,23.86,6.141,27,10.001,27h10C23.86,27,27,23.859,27,19.999v-10   C27,6.14,23.859,3,19.999,3z M15,21c-3.309,0-6-2.691-6-6s2.691-6,6-6s6,2.691,6,6S18.309,21,15,21z M22,9c-0.552,0-1-0.448-1-1   c0-0.552,0.448-1,1-1s1,0.448,1,1C23,8.552,22.552,9,22,9z"
              ></path>
            </svg>
          </a>
          <a href="/" class="text-gray-500 transition-colors duration-300 hover:text-deep-purple-accent-400">
            <svg viewBox="0 0 24 24" fill="currentColor" class="h-5">
              <path
                d="M22,0H2C0.895,0,0,0.895,0,2v20c0,1.105,0.895,2,2,2h11v-9h-3v-4h3V8.413c0-3.1,1.893-4.788,4.659-4.788 c1.325,0,2.463,0.099,2.795,0.143v3.24l-1.918,0.001c-1.504,0-1.795,0.715-1.795,1.763V11h4.44l-1,4h-3.44v9H22c1.105,0,2-0.895,2-2 V2C24,0.895,23.105,0,22,0z"
              ></path>
            </svg>
          </a>
        </div>
        <p class="mt-4 text-sm text-gray-500">
          Bacon ipsum dolor amet short ribs pig sausage prosciutto chicken spare ribs salami.
        </p>
      </div>
    </div>
    <div class="flex flex-col-reverse justify-between pt-5 pb-10 border-t lg:flex-row">
      <p class="text-sm text-gray-600">
        © Copyright 2021 <%= link_to "Superails. ", root_path, class: "text-sm text-pink-600 transition-colors duration-300 hover:text-pink-accent-400 #{'active' if current_page?(root_path)}" %>All rights reserved.
      </p>
      <ul class="flex flex-col mb-3 space-y-2 lg:mb-0 sm:space-y-0 sm:space-x-5 sm:flex-row">
        <li>
          <%= link_to pricing_path, class: "text-sm text-gray-600 transition-colors duration-300 hover:text-pink-accent-400 #{'active' if current_page?(pricing_path)}" do %>
            About
          <% end %>
        </li>
        <li>
          <%= link_to pricing_path, class: "text-sm text-gray-600 transition-colors duration-300 hover:text-pink-accent-400 #{'active' if current_page?(pricing_path)}" do %>
            Pricing
          <% end %>
        </li>
        <li>
          <%= link_to privacy_path, class: "text-sm text-gray-600 transition-colors duration-300 hover:text-pink-accent-400 #{'active' if current_page?(privacy_path)}" do %>
            Privacy Policy
          <% end %>
        </li>
        <li>
          <%= link_to terms_path, class: "text-sm text-gray-600 transition-colors duration-300 hover:text-pink-accent-400 #{'active' if current_page?(terms_path)}" do %>
            Terms &amp; Conditions
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header id="header" class="header">
  <nav class="bg-white shadow-lg">
    <div class="container flex flex-wrap items-center justify-between px-2 py-3 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl">
      <div class="relative flex items-center justify-center justify-between w-3/12 lg:w-auto lg:static lg:block lg:justify-start lg:w-2/12">
        <%= link_to root_path, class:"flex items-center space-x-3" do %>
          <%= image_tag "favicon.ico", height: "20", alt: "logo", class: "inline-block align-top w-10" %>
          <h1 class="ml-1 text-2xl font-extrabold tracking-wide text-indigo-800 uppercase font-display">SupeRails</h1>
        <% end %>
      </div>
      <div class="relative flex-row flex-wrap items-center justify-center flex-grow w-9/12 h-full mr-0 lg:flex group lg:w-7/12">
        <ul class="flex items-center space-x-8 list-none lg:flex-row lg:ml-auto">
            <%= render navigation_links_partial_path %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="card-body list-group-item-<%= key.to_s == 'notice' ? 'success' : 'danger' %>" role="message">
    <a data-dismiss="message" href="#">
      <i class="fa fa-times"></i>
    </a>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_vimeo.html.erb
<div style="padding:66.67% 0 0 0;position:relative;">
  <iframe src="https://player.vimeo.com/video/<%= vimeo_id %>?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479&amp;h=696765de8b" 
    frameborder="0" 
    allow="autoplay; fullscreen; picture-in-picture"
    allowfullscreen 
    style="position:absolute;top:0;left:0;width:100%;height:100%;" 
    title="12 stripe course promo shoplify and saasblog">
  </iframe>
</div>
<script src="https://player.vimeo.com/api/player.js">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= display_meta_tags site: Rails.application.class.module_parent.name,
                          description: 'Moder Ruby on Rails screencasts',
                          keywords: 'ruby, rails, ruby-on-rails' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "favicon.ico" %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag '/assets/icons/favicon.ico', rel: 'apple-touch-icon', type: 'image/ico' %>
  </head>
  <body class="flex flex-col flex-auto min-h-screen antialiased leading-normal text-gray-900 font-body" data-controller-name=<%= controller_name %> data-action-name=<%= action_name %>>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/header' %>
    <main class="container px-5 mx-auto mt-20" id="content">
        <%= yield %>
    </main>
  </body>
  <footer>
    <br>
    <%= render 'layouts/footer' %>
  </footer>
</html>