config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                   confirmations: 'users/confirmations',
                   registrations: 'users/registrations'
                 }
  root 'static_public#landing_page'
  get 'privacy', to: 'static_public#privacy'
  get 'terms', to: 'static_public#terms'
  get 'pricing', to: 'static_public#pricing'
  get 'about', to: 'static_public#about'

  resources :comments, only: [] do
    resources :comments, only: %i[new create destroy], module: :comments
  end

  resources :posts do
    resources :comments, only: %i[new create destroy], module: :posts
    member do
      patch "upvote", to: "posts#upvote"
      patch "downvote", to: "posts#downvote"
      patch "bookmark", to: "posts#bookmark"
      patch "complete", to: "posts#complete"
      patch "watchlist", to: "posts#watchlist"
    end
  end

  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  resources :webhooks, only: [:create]

  resources :users, only: %i[index show]

  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper

  # navigation links
  def navigation_links_partial_path
    if user_signed_in?
      'layouts/navigation/signed_in_links'
    else
      'layouts/navigation/non_signed_in_links'
    end
  end
end

app/views/layouts/navigation/_dropdown_menu.html.erb
<li>
  <div
    data-controller="dropdown"
    data-action="click->dropdown#toggle click@window->dropdown#hide"
    data-dropdown-open-value="false"
    data-dropdown-active-target="#dropdown-button"
    data-dropdown-active-class="bg-white"
    data-dropdown-invisible-class="scale-95 opacity-0"
    data-dropdown-visible-class="scale-100 opacity-100"
    data-dropdown-entering-class="duration-300 ease-out"
    data-dropdown-enter-timeout="300"
    data-dropdown-leaving-class="duration-300 ease-in"
    data-dropdown-leave-timeout="300"
    aria-haspopup="true"
    aria-expanded="false">

    <div id="dropdown-button" class="relative inline-block px-4 py-2 mt-0 text-sm font-bold leading-none text-white no-underline bg-pink-600 rounded">

      <div role="button" tabindex="0" data-dropdown-target="button" class="inline-block select-none">
        <span class="flex items-center inline-block appearance-none">
          <span><%= current_user.name.upcase %></span>
        </span>
      </div>

      <div data-dropdown-target="menu" class="absolute right-0 z-10 hidden mt-2 transition transform scale-100 opacity-0 top-10">
        <div class="overflow-hidden text-base font-medium text-left bg-white border rounded shadow w-60">
          <p class="flex flex-wrap block py-3 pl-4 text-gray-900 no-underline whitespace-no-wrap bg-white border-b">
            <span class="w-full font-medium"><%= current_user.name.capitalize if signed_in? %></span>
            <small class="w-full text-gray-500"><%= current_user.email %> </small>
          </p>

            <ul>

              <%= deep_active_link_to_dropdown_item new_post_path do %>
                <svg class="justify-center w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path></svg>
                <span class="mx-3">Write a new post</span>
                <% end %>

              <%= deep_active_link_to_dropdown_item user_path(current_user) do %>
                <svg class="justify-center w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
                <span class="mx-3">My Profile</span>
              <% end %>

              <%= deep_active_link_to_dropdown_item users_path do %>
              <svg class="justify-center w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z"></path></svg>
              <span class="mx-3">Community</span>
              <% end %>

              <%= deep_active_link_to_dropdown_item edit_user_registration_path do %>
                <svg class="justify-center w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path></svg>
                <span class="mx-3">Account Settings</span>
              <% end %>

              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: "flex items-center flex-wrap text-sm block py-3 pl-4 text-gray-900 no-underline whitespace-no-wrap bg-white hover:bg-pink-500 hover:text-white border-t" do %>
                  <svg class="justify-center w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 3a1 1 0 00-1 1v12a1 1 0 102 0V4a1 1 0 00-1-1zm10.293 9.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3a1 1 0 10-1.414 1.414L14.586 9H7a1 1 0 100 2h7.586l-1.293 1.293z" clip-rule="evenodd"></path></svg>
                  <span class="mx-3">Sign Out</span>
                <% end %>
              </li>
            </ul>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/layouts/navigation/_non_signed_in_links.html.erb
<%= deep_active_link_to pricing_path do %>
  Pricing
<% end %>
<%= deep_active_link_to posts_path do %>
  Posts
<% end %>
<%= active_link_to "Log in", new_user_session_path %>
<%= active_link_to "Sign up", new_user_registration_path %>

app/views/layouts/navigation/_signed_in_links.html.erb
<%= deep_active_link_to pricing_path do %>
  Pricing
<% end %>
<%= deep_active_link_to posts_path do %>
  Posts
<% end %>
<% if current_user %>
  <%= link_to "Manage Billing", billing_portal_create_path, method: :post, data: { disable_with: "validating..."}, class: 'nav-link' %>
  <%= deep_active_link_to new_post_path do %>
    New Post
  <% end %>
  <%= deep_active_link_to users_path do %>
    Users
  <% end %>
  <%= deep_active_link_to new_user_invitation_path do %>
    Invite friend
  <% end %>
<% end %>
<%= render 'layouts/navigation/dropdown_menu' %>